name: Generate, Sign, and Commit SBOM

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  generate-and-sign-sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Syft
        run: |
          SYFT_VERSION="1.28.0"
          curl -sSfL https://github.com/anchore/syft/releases/download/v${SYFT_VERSION}/syft_${SYFT_VERSION}_linux_amd64.tar.gz | tar -xz
          sudo mv syft /usr/local/bin/
          syft version

      - name: Generate SBOM in SPDX JSON format
        run: |
          syft dir:. -o spdx-json --file log4shell-vulnerable-app-spdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: SBOM
          path: log4shell-vulnerable-app-spdx.json

      - name: Install Cosign
        run: |
          COSIGN_VERSION="v2.2.3"
          wget https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64
          chmod +x cosign-linux-amd64
          sudo mv cosign-linux-amd64 /usr/local/bin/cosign

      - name: Sign SBOM
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign-blob --yes --oidc-issuer="https://token.actions.githubusercontent.com" \
            --output-certificate log4shell-vulnerable-app-spdx.pem \
            log4shell-vulnerable-app-spdx.json

      - name: Commit SBOM and signature
        run: |
          git config --local user.email "simlixincarrie02@gmail.com"
          git config --local user.name "carrieesim"
          git add log4shell-vulnerable-app-spdx.json log4shell-vulnerable-app-spdx.pem
          git commit -m "Add and sign SBOM" || echo "No changes to commit"
          git pull --rebase origin master || true
          git push || echo "Nothing to push"

  vulnerability-analysis:
    needs: generate-and-sign-sbom
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download SBOM artifact
        uses: actions/download-artifact@v4
        with:
          name: SBOM

      - name: Install Grype
        run: |
          GRYPE_VERSION="0.88.0"
          curl -sSfL https://github.com/anchore/grype/releases/download/v${GRYPE_VERSION}/grype_${GRYPE_VERSION}_linux_amd64.tar.gz | tar -xz
          sudo mv grype /usr/local/bin/
          grype version

      - name: Validate SBOM JSON
        run: |
          head -40 log4shell-vulnerable-app-spdx.json
          jq empty log4shell-vulnerable-app-spdx.json

      - name: Run vulnerability analysis with JSON output
        id: grype_scan
        run: |
          grype sbom:log4shell-vulnerable-app-spdx.json -o json > grype_results.json
          VULN_COUNT=$(jq '.matches | length' grype_results.json)
          echo "Vulnerability count: $VULN_COUNT"
          echo "vuln_count=$VULN_COUNT" >> $GITHUB_OUTPUT

      - name: Notify Teams via Power Automate
        if: steps.grype_scan.outputs.vuln_count != '0'
        run: |
          cat <<EOF > card.json
{
  "\$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.4",
  "body": [
    {
      "type": "TextBlock",
      "text": "🚨 Vulnerability Detected in SBOM",
      "weight": "Bolder",
      "size": "Medium",
      "color": "Attention"
    },
    {
      "type": "TextBlock",
      "text": "A total of ${{
        steps.grype_scan.outputs.vuln_count
      }} vulnerabilities were detected during SBOM scanning.",
      "wrap": true
    },
    {
      "type": "TextBlock",
      "text": "**Repository**: ${{ github.repository }}",
      "wrap": true
    },
    {
      "type": "TextBlock",
      "text": "**Branch**: ${{ github.ref_name }}",
      "wrap": true
    },
    {
      "type": "TextBlock",
      "text": "**Commit SHA**: ${{ github.sha }}",
      "wrap": true
    },
    {
      "type": "TextBlock",
      "text": "🔗 [View Workflow Logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})",
      "wrap": true
    }
  ]
}
EOF
          curl -X POST -H "Content-Type: application/json" \
            -d @card.json \
            "${{ secrets.TEAMS_WEBHOOK }}"
